---
- hosts: all
  become: yes
  tasks:
    - name: Désactiver l'authentification par mot de passe SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH
