---
- hosts: all
  become: yes
  tasks:
    - name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('pub', '/root/ansible_test') }}"